# Generated by Django 4.2.3 on 2023-07-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='credit',
        ),
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.student')),
            ],
        ),
    ]
