# Generated by Django 4.2.3 on 2023-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_credit_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('student', 'lesson')},
        ),
    ]
